// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqrrxrxzrcuebsuojnnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxcnJ4cnh6cmN1ZWJzdW9qbm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NDI4MDksImV4cCI6MjA1NTExODgwOX0.SCAoUnUt4T8bAt5f_-QTrPjXiq3gzv7c3xhj4mMkv3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);